"""Chemins canoniques du projet.

Ce module centralise les chemins de lecture/écriture afin que les scripts
réorganisés sous ``src/`` utilisent tous la même structure de projet.
"""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"

RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
TEST_DATA_DIR = DATA_DIR / "test"

DATABASE_CONSTRUCTION_RESULTS_DIR = RESULTS_DIR / "database-construction"
DATABASE_MERGED_DATA_DIR = DATABASE_CONSTRUCTION_RESULTS_DIR / "merged-data"
DATABASE_CLEANED_DATA_DIR = DATABASE_CONSTRUCTION_RESULTS_DIR / "cleaned-data"
DATABASE_VARIABLE_PREPARATION_DIR = DATABASE_CONSTRUCTION_RESULTS_DIR / "variable-preparation"
DATABASE_SPLIT_DATASETS_DIR = DATABASE_CONSTRUCTION_RESULTS_DIR / "split-datasets"
DATABASE_SPLIT_DIAGNOSTICS_DIR = DATABASE_CONSTRUCTION_RESULTS_DIR / "split-diagnostics"

CSDS_IMPLEMENTATION_RESULTS_DIR = RESULTS_DIR / "csds-implementation"
CSDS_VALIDATION_RESULTS_DIR = CSDS_IMPLEMENTATION_RESULTS_DIR / "validation"
CSDS_RECONSTRUCTED_CURVES_DIR = CSDS_IMPLEMENTATION_RESULTS_DIR / "reconstructed-curves"
CSDS_FITTED_PARAMETERS_DIR = CSDS_IMPLEMENTATION_RESULTS_DIR / "fitted-parameters"
CSDS_CONVERGED_CASES_DIR = CSDS_IMPLEMENTATION_RESULTS_DIR / "converged-cases"
CSDS_COMPARISON_RESULTS_DIR = CSDS_IMPLEMENTATION_RESULTS_DIR / "comparisons"

DESCRIPTIVE_STATS_RESULTS_DIR = RESULTS_DIR / "descriptive-stats"
SCATTER_PLOTS_RESULTS_DIR = RESULTS_DIR / "scatter-plots"
HISTOGRAMS_RESULTS_DIR = RESULTS_DIR / "histograms"

METHODOLOGIE_1_RESULTS_DIR = RESULTS_DIR / "methodologie_1"
METHODOLOGIE_1_HEURISTIC_DIR = METHODOLOGIE_1_RESULTS_DIR / "heuristic"
METHODOLOGIE_1_CROSS_VALIDATION_DIR = METHODOLOGIE_1_RESULTS_DIR / "cross_validation"
METHODOLOGIE_1_RECONSTRUCTED_DIR = METHODOLOGIE_1_RESULTS_DIR / "reconstructed_parameters"
METHODOLOGIE_1_FIGURES_DIR = METHODOLOGIE_1_RESULTS_DIR / "figures"

METHODOLOGIE_2_RESULTS_DIR = RESULTS_DIR / "methodologie_2"
METHODOLOGIE_2_HEURISTIC_DIR = METHODOLOGIE_2_RESULTS_DIR / "heuristic"
METHODOLOGIE_2_CROSS_VALIDATION_DIR = METHODOLOGIE_2_RESULTS_DIR / "cross_validation"
METHODOLOGIE_2_RECONSTRUCTED_DIR = METHODOLOGIE_2_RESULTS_DIR / "reconstructed_parameters"
METHODOLOGIE_2_FIGURES_DIR = METHODOLOGIE_2_RESULTS_DIR / "figures"

COMPARISON_RESULTS_DIR = RESULTS_DIR / "comparison"
FINAL_RESULTS_DIR = RESULTS_DIR / "final-results"
FINAL_RECURRENT_VARIABLES_DIR = FINAL_RESULTS_DIR / "recurrent-variables"
FINAL_PCA_DIR = FINAL_RESULTS_DIR / "pca"
FINAL_LAMBDA_SEARCH_DIR = FINAL_RESULTS_DIR / "lambda-search"
FINAL_REGULARIZED_REGRESSION_DIR = FINAL_RESULTS_DIR / "regularized-regression"
FINAL_MODEL_COMPARISON_DIR = FINAL_RESULTS_DIR / "model-comparison"
FINAL_INDEPENDENT_DATASET_DIR = FINAL_RESULTS_DIR / "independent-dataset"

RESIDUAL_ANALYSIS_RESULTS_DIR = RESULTS_DIR / "residual-analysis"
MISC_RESULTS_DIR = RESULTS_DIR / "misc"

MATPLOTLIB_CACHE_DIR = PROJECT_ROOT / ".matplotlib_cache"


def ensure_directory(path: Path) -> Path:
    """Crée un dossier et retourne le chemin pour chaînage."""
    path.mkdir(parents=True, exist_ok=True)
    return path


def ensure_results_structure() -> None:
    """Crée l'arborescence canonique des sorties."""
    for path in [
        RESULTS_DIR,
        DATABASE_CONSTRUCTION_RESULTS_DIR,
        DATABASE_MERGED_DATA_DIR,
        DATABASE_CLEANED_DATA_DIR,
        DATABASE_VARIABLE_PREPARATION_DIR,
        DATABASE_SPLIT_DATASETS_DIR,
        DATABASE_SPLIT_DIAGNOSTICS_DIR,
        CSDS_IMPLEMENTATION_RESULTS_DIR,
        CSDS_VALIDATION_RESULTS_DIR,
        CSDS_RECONSTRUCTED_CURVES_DIR,
        CSDS_FITTED_PARAMETERS_DIR,
        CSDS_CONVERGED_CASES_DIR,
        CSDS_COMPARISON_RESULTS_DIR,
        DESCRIPTIVE_STATS_RESULTS_DIR,
        SCATTER_PLOTS_RESULTS_DIR,
        HISTOGRAMS_RESULTS_DIR,
        METHODOLOGIE_1_RESULTS_DIR,
        METHODOLOGIE_1_HEURISTIC_DIR,
        METHODOLOGIE_1_CROSS_VALIDATION_DIR,
        METHODOLOGIE_1_RECONSTRUCTED_DIR,
        METHODOLOGIE_1_FIGURES_DIR,
        METHODOLOGIE_2_RESULTS_DIR,
        METHODOLOGIE_2_HEURISTIC_DIR,
        METHODOLOGIE_2_CROSS_VALIDATION_DIR,
        METHODOLOGIE_2_RECONSTRUCTED_DIR,
        METHODOLOGIE_2_FIGURES_DIR,
        COMPARISON_RESULTS_DIR,
        FINAL_RESULTS_DIR,
        FINAL_RECURRENT_VARIABLES_DIR,
        FINAL_PCA_DIR,
        FINAL_LAMBDA_SEARCH_DIR,
        FINAL_REGULARIZED_REGRESSION_DIR,
        FINAL_MODEL_COMPARISON_DIR,
        FINAL_INDEPENDENT_DATASET_DIR,
        RESIDUAL_ANALYSIS_RESULTS_DIR,
        MISC_RESULTS_DIR,
        MATPLOTLIB_CACHE_DIR,
    ]:
        path.mkdir(parents=True, exist_ok=True)
